bedroom_choices = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5':5,
    '6':6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10':10,

}

price_choices = {
                "100000":"GHC100,000",
                "200000":"GHC200,000",
                "300000":"GHC300,000",
                "400000":"GHC400,000",
                "500000":"GHC500,000",
                "600000":"GHC600,000",
                "700000":"GHC700,000",
                "800000":"GHC800,000",
                "900000":"GHC900,000",
                "1000000":"GHC1M+",
}

state_choices = {
                "AL":"Alabama",
                   "AK":"Alaska",
                   "AZ":"Arizona",
                   "AR":"Arkansas",
                   "CA":"California",
                   "CO":"Colorado",
                   "CT":"Connecticut",
                   "DE":"Delaware",
                   "DC":"District Of Columbia",
                   "FL":"Florida",
                   "GA": "Georgia",
                   "GH": "Ghana",
                   "HI":"Hawaii",
                   "ID":"Idaho",
                   "IL":"Illinois",
                   "IN":"Indiana",
                   "IA":"Iowa",
                   "KS":"Kansas",
                   "KY":"Kentucky",
                   "LA":"Louisiana",
                   "ME":"Maine",
                   "MD":"Maryland",
                   "MA":"Massachusetts",
                   "MI":"Michigan",
                   "MN":"Minnesota",
                   "MS":"Mississippi",
                   "MO":"Missouri",
                   "MT":"Montana",
                   "NE":"Nebraska",
                   "NV":"Nevada",
                   "NH":"New Hampshire",
                   "NJ":"New Jersey",
                   "NM":"New Mexico",
                   "NY":"New York",
                   "NC":"North Carolina",
                   "ND":"North Dakota",
                   "OH":"Ohio",
                   "OK":"Oklahoma",
                   "OR":"Oregon",
                   "PA":"Pennsylvania",
                   "RI":"Rhode Island",
                   "SC":"South Carolina",
                   "SD":"South Dakota",
                   "TN":"Tennessee",
                   "TX":"Texas",
                   "UT":"Utah",
                   "VT":"Vermont",
                   "VA":"Virginia",
                   "WA":"Washington",
                   "WV":"West Virginia",
                   "WI":"Wisconsin",
                   "WY":"Wyoming",
}